- .coveragerc
Fixes #77
Omit migrations, admin configuration, and settings
> Omit untested files from coverage report

- km_api/know_me/tests/models/test_km_user_model.py
> Restore tests for KMUser model.

- km_api/know_me/models.py
- km_api/know_me/tests/models/test_model_functions.py
Addresses #88 , however I am not entirely sure this is the desired path for media resources. It is now the same as the path for upload_to of the KMUser model.
> Change upload path for media resource

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
These templates would provide a starting point for creating issues and pull requests. I don't know if we want or need them, but I think it would be nice.
> Add pull request and issue templates

- km_api/know_me/filters.py
- km_api/know_me/tests/filters/test_media_resource_filter_backend.py
- km_api/know_me/views.py
This prevents users from listing media resources they don't have access to.
Closes #119
> Add filter backend for listing media resources

- docs/conf.py
This changes updates the copyright information in the documentation.
Closes #104
> Set 'Know Me Inc' as author and copyright holder.

- docs/deployment.rst
Fixes #174 
This PR updates the documentation about deployment. The result can be seen [here](http://know-me-api.readthedocs.io/en/bugfix-issue-174-deploy-docs/deployment.html).
> Update deployment docs

- deploy/env_vars/base.yml
- deploy/group_vars/amibuilder/main.yml
- deploy/roles/provision-autoscaling-group/defaults/main.yml
- deploy/roles/provision-autoscaling-group/tasks/main.yml
Fixes #178 
This PR fixes the deployment, particularly connections over HTTPS.
> Fix site deployment

- deploy/env_vars/base.yml
Fixes #171 
This PR updates the version of the OS that our webservers run on. The new release contains a fix for CVE-2017-7533.
> Update base AMI.

- docs/API/know-me-profile.rst
Closes #25
Update the profile topic docs to include the options available for the topic type.
> Improve profile topic type docs

- docs/API/know-me-sharing.rst
- docs/api-endpoints.rst
- km_api/know_me/tests/views/test_accessor_detail_view.py
- km_api/know_me/tests/views/test_accessor_list_view.py
- km_api/know_me/urls.py
- km_api/know_me/views.py
Closes #139
This PR adds views for managing the sharing settings for a Know Me user's account.
> Add views for managing sharing settings

- docs/API/know-me-sharing.rst
- km_api/conftest.py
- km_api/know_me/tests/views/test_pending_accessor_list_view.py
- km_api/know_me/urls.py
- km_api/know_me/views.py
Closes #198
This PR adds an endpoint to list the accessors that need to be accepted or declined by the requesting user.
> Add view to list pending accessors.

- km_api/know_me/tests/views/test_accessor_detail_view.py
- km_api/know_me/views.py
Fixes #201
The accessor list now requires the user be authenticated.
> Require authentication for accessor list

- .travis.yml
Closes #220
Remove slack notifications from the Travis CI build.
> Remove slack notifications for Travis CI.

- km_api/conftest.py
- km_api/know_me/permissions.py
- km_api/know_me/tests/permissions/test_has_km_user_access.py
- km_api/know_me/tests/views/test_media_resource_list_view.py
- km_api/know_me/urls.py
- km_api/know_me/views.py
Closes #213
This PR adds an endpoint for listing and creating media resources.
> Add media resource list view.

- km_api/know_me/tests/views/test_media_resource_list_view.py
- km_api/know_me/views.py
Closes #213 
This PR adds the ability to filter media resources by category.
> Allow media resources to be filtered by category.

- docs/changelog.rst
- km_api/know_me/tests/views/test_profile_item_detail_view.py
- km_api/know_me/views.py
> Fix crash when viewing documentation

- docs/changelog.rst
- km_api/know_me/journal/serializers.py
- km_api/know_me/journal/tests/integration/test_entry_list_view.py
- km_api/know_me/journal/tests/serializers/test_entry_detail_serializer.py
- km_api/know_me/journal/tests/serializers/test_entry_list_serializer.py
- km_api/know_me/journal/tests/views/test_entry_list_view.py
- km_api/know_me/journal/urls.py
- km_api/know_me/journal/views.py
- km_api/know_me/urls.py
> Add endpoint for listing and creating journal entries

- km_api/know_me/journal/models.py
- km_api/know_me/journal/tests/integration/test_entry_detail_view.py
- km_api/know_me/journal/tests/integration/test_entry_list_view.py
- km_api/know_me/journal/tests/models/test_entry_model.py
- km_api/know_me/journal/tests/views/test_entry_detail_view.py
- km_api/know_me/journal/urls.py
- km_api/know_me/journal/views.py
> Add endpoint to manage journal entries.

- km_api/know_me/journal/models.py
- km_api/know_me/journal/serializers.py
- km_api/know_me/journal/tests/integration/test_entry_comment_detail_view.py
- km_api/know_me/journal/tests/models/test_entry_comment_model.py
- km_api/know_me/journal/tests/serializers/test_entry_comment_serializer.py
- km_api/know_me/journal/tests/views/test_entry_comment_detail_view.py
- km_api/know_me/journal/urls.py
- km_api/know_me/journal/views.py
> Add detail endpoint for journal comments

- km_api/know_me/profile/urls.py
> Nest profile URLs under 'know-me/profile/` path.

- deploy/ansible/group_vars/webservers/main.yml
- docs/changelog.rst
- km_api/km_api/settings.py
- km_api/know_me/journal/apps.py
- km_api/know_me/journal/search_adapters.py
- km_api/know_me/journal/tests/views/test_entry_list_view.py
- km_api/know_me/journal/views.py
- requirements/base.txt
Closes #250 
This PR adds the ability to search journal entries by keyword and by publication time.
> Add searching for journal entries

- docs/changelog.rst
- km_api/know_me/signals.py
- km_api/know_me/tests/signals/test_create_km_user_signal.py
- requirements/base.txt
Closes #263 
Closes #277
When a new user registers, a Know Me user is created for them
automatically.
> Automatically create Know Me users.

- docs/changelog.rst
- km_api/account/serializers.py
- km_api/account/tests/serializers/test_user_serializer.py
> Add 'is_staff' to user detail endpoint.

- docs/changelog.rst
- km_api/know_me/tests/integration/test_accepted_accessor_list_view.py
- km_api/know_me/tests/views/test_accepted_accessor_list_view.py
- km_api/know_me/urls.py
- km_api/know_me/views.py
> Add endpoint to list accepted accessors.

- .coveragerc
- .travis.yml
- Pipfile.lock
- docs/changelog.rst
- km_api/conftest.py
- km_api/factories.py
- km_api/functional_tests/account/test_verify_email.py
- km_api/functional_tests/conftest.py
- km_api/km_api/settings.py
- km_api/pytest.ini
Closes #393
In deference to useability concerns, users now only need the token that they were emailed to verify their email address.
> Disable password requirement to verify email

- km_api/factories.py
Refactor user factory to use a related factory instead of writing our
own version using a post-generation hook.
> Refactor email creation during testing

- .coveragerc
- km_api/functional_tests/status/test_get_status.py
- km_api/km_api/urls.py
- km_api/status/test/views/test_health_check_view.py
- km_api/status/urls.py
- km_api/status/views.py
Closes #420 
The status check endpoint returns a 503 response if there are unapplied migrations and a 200 response otherwise.
> Add status check endpoint

- Pipfile
- Pipfile.lock
- km_api/km_api/settings.py
Closes #422
Upgrade to new Sentry SDK.
> Upgrade to new Sentry SDK

- docker-entrypoint.sh
- km_api/know_me/management/commands/updatesubscriptions.py
- km_api/know_me/tests/management/commands/test_updatesubscriptions_command.py
Closes #385
This management command is intended to be run periodically to update the status of Know Me premium subscriptions.
> Add command to update subscription statuses

- .travis.yml
Closes #448 
Add a Travis CI build that makes sure the Docker image for the application is buildable.
> Add tests for building Docker image

- Pipfile
- Pipfile.lock
- docs/conf.py
Bump dependency versions including a fix for `urllib3`'s most recent security notice.
> Bump dependency versions

- Pipfile.lock
- km_api/functional_tests/account/test_register.py
Closes #468
Closes #483
This includes a fix for the user's first email not being registered as their primary address.
> Update email authentication library version

- .idea/codeStyles/Project.xml
- .idea/codeStyles/codeStyleConfig.xml
- km_api/apple/receipts.py
- km_api/apple/serializers.py
- km_api/apple/test/receipts/test_get_receipt_info.py
- km_api/apple/test/serializers/test_receipt_type_serializer.py
- km_api/apple/test/views/test_receipt_type_query_view.py
- km_api/apple/urls.py
- km_api/apple/views.py
- km_api/functional_tests/test_get_apple_receipt_type.py
- km_api/km_api/settings.py
- km_api/km_api/urls.py
- km_api/know_me/subscriptions.py
- km_api/know_me/tests/subscriptions/test_validate_apple_receipt.py
Closes #494
The endpoint allows the caller to determine if the receipt corresponds
to Apple's production or sandbox environment.
> Add endpoint to determine Apple receipt type

- km_api/km_api/settings.py
Closes #508
Switch account used to send emails from `no-reply@knowmetools.com` to `no-reply@knowme.works`.
> Update the email address the API sends from
