knowmetools/km-api

km_api/account/authentication.py
km_api/account/serializers.py
km_api/account/tests/authentication/test_authentication_backend.py
km_api/km_auth/serializers.py

This change restores the more descriptive error message that was previously present for users who try to log in with an unverified email address. Rather than giving them an `invalid credentials` response, we tell them that their email needs to be verified before they can sign in.
A side effect of this change is that we had to revert #60.
Fixes #70

Unverified email login message

---

docs/changelog.rst
km_api/know_me/tests/views/test_km_user_detail_view.py
km_api/know_me/tests/views/test_km_user_list_view.py
km_api/know_me/urls.py
km_api/know_me/views.py

The new endpoints mirror the functionality of the existing `/know-me/profiles/*` endpoints. All that was required was a little cleanup.
Closes #93

Update Know Me user endpoints

---

.travis.yml

When we set the default option for tests to run in parallel, it broke the coverage report from Travis CI.

Fix coverage report for CI build.

---

docs/API/know-me-profile.rst
km_api/know_me/serializers/__init__.py
km_api/know_me/serializers/profile_item_content_serializers.py
km_api/know_me/serializers/profile_item_serializers.py
km_api/know_me/tests/serializers/test_list_content_serializer.py
km_api/know_me/tests/serializers/test_list_entry_serializer.py
km_api/know_me/tests/serializers/test_profile_item_serializer.py
km_api/know_me/tests/views/test_profile_item_detail_view.py
km_api/know_me/tests/views/test_profile_item_list_view.py

Profile items can now be created with list content or image content.
These options are mutually exclusive and cannot be changed once a
profile item is created.
Closes #100

Add list content to profile item serializer

---

km_api/know_me/serializers/fields.py
km_api/know_me/tests/serializers/fields/test_media_resource_field.py
km_api/know_me/tests/serializers/test_emergency_item_serializer.py
km_api/know_me/tests/serializers/test_image_content_serializer.py

The queryset for the media resource field is now limited to the
resources owned by the Know Me user provided to the field as context.
Fixes #110

Limit choices for media resource field.

---

km_api/know_me/filters.py
km_api/know_me/tests/filters/test_emergency_item_filter_backend.py
km_api/know_me/views.py

This filter backend prevents users from accessing emergency items they don't have access to.
Closes #118

Add filter backend for emergency items

---

km_api/know_me/tests/serializers/test_profile_detail_serializer.py
km_api/know_me/tests/serializers/test_profile_list_serializer.py

Fixes #150
These were old test_profile_group_detail_serializer and test_profile_group_list_serializer tests, went through to change the names.

Restore missing profile serializer tests.

---

km_api/account/models.py
km_api/account/tests/models/test_user_model.py
km_api/km_auth/serializers.py
km_api/km_auth/tests/serializers/test_user_registration_serializer.py

Closes #137 
This PR adds support for registering a pending user. If there is a user with `is_pending == True` whose email matches the email given when a user registers, then the pending user is updated using the provided information.

Add logic to handle pending user registration

---

km_api/account/tests/conftest.py
km_api/conftest.py
km_api/km_auth/tests/conftest.py
km_api/know_me/models.py
km_api/know_me/tests/models/test_km_user_model.py

Closes #131
This PR adds a `share` method to the `KMUser` model. This method allows for sharing of a Know Me user's account.
One issue that I see with this approach is the following
1. User invited by email
2. Account doesn't exist, so pending user created
3. Existing user changes their email address to the one used to create the invitation in step 1.
Now the pending user can't sign up because the email address is already in use. Admittedly this is a really niche issue that I don't expect to happen that often. Still, is this something we want to worry about?

Add 'share' method for Know Me users.

---

.bumpversion.cfg
deploy/group_vars/amibuilder/main.yml

Closes #160
This PR adds release tracking with Sentry. The version number is bumped automatically with the rest of our versioning logic.

Add release tracking with Sentry

---

km_api/know_me/filters.py
km_api/know_me/tests/filters/test_km_user_filter_backend.py

Addresses #173
This PR updates the `KMUserFilterBackend` to also return `KMUser` instances that the requesting user has been invited to.
The one thing left to do here is determine the behavior for unaccepted invitations. My current thoughts are that we should exclude them from this list and have a separate request for a user to view their pending invitations.

Update KMUser filter backend to respect sharing

---

deploy/group_vars/amibuilder/main.yml
deploy/requirements.yml
requirements.txt

Closes #175 
This PR configures logging to CloudWatch. This is important because previously we were logging to a file, but we didn't have the ability to access that file.

Set up logging with CloudWatch.

---

km_api/know_me/filters.py
km_api/know_me/tests/filters/test_km_user_filter_backend.py

Fixes #182
If there is no issue to reference for the proposed changes, please consider opening one so we can discuss if the changes are needed.
The list returned by `/know-me/users/` now does not include users where the `KMUserAccessor` is not marked as 'accepted'.

Exclude unaccepted shares from KMUser list.

---

km_api/know_me/filters.py
km_api/know_me/tests/filters/test_emergency_contact_filter_backend.py

Addresses #173 
This PR updates the `EmergencyContactFilterBackend` to allow access to the emergency contacts of a shared `KMUser`.

Update emergency contact filter to allow sharing

---

km_api/know_me/serializers/__init__.py
km_api/know_me/serializers/km_user_accessor_serializers.py
km_api/know_me/tests/serializers/test_km_user_accessor_serializer.py

Not ready for review.
Fixes #134 
Serializer for KMUser access model.

Serializer for KMUserAccessor Model

---

km_api/know_me/serializers/km_user_accessor_serializers.py
km_api/know_me/tests/serializers/test_km_user_accessor_serializer.py
km_api/know_me/tests/views/test_accessor_detail_view.py
km_api/know_me/views.py

Closes #197 
This PR allows users to mark accessors granting them access to an account as "accepted".

Allow accessors to be accepted

---

docs/API/know-me-sharing.rst
km_api/know_me/models.py
km_api/know_me/serializers/km_user_accessor_serializers.py
km_api/know_me/tests/models/test_km_user_accessor_model.py
km_api/know_me/tests/serializers/test_km_user_accessor_serializer.py
km_api/know_me/tests/views/test_accessor_detail_view.py

Closes #202
This PR adds the URL of the accessor's detail view to the accessor serializer.

Add detail URL to accessor serializer

---

km_api/know_me/serializers/km_user_accessor_serializers.py
km_api/know_me/tests/serializers/test_km_user_accessor_serializer.py

Closes #203
The KMUserAccessorSerializer now only returns the information from the
KMUserListSerializer rather than the full KMUserDetailSerializer.

Trim down km_user info for accessor serializer.

---

km_api/know_me/filters.py
km_api/know_me/tests/filters/test_km_user_access_filter_backend.py

Fixes #224
Use the default filter backend base provided by DRF instead of the one from `dry-rest-permissions`.

Fix issue with filters not being applied.

---

km_api/know_me/tests/views/test_profile_item_list_view.py
km_api/know_me/views.py

Closes #219
The places where we override 'get_serializer_context' now include checks
for kwargs not existing due to the way the documentation is generated.

Make get_serializer_context safer

---

.travis.yml
km_api/know_me/models.py
km_api/know_me/serializers/__init__.py
km_api/know_me/serializers/media_resource_serializers.py
km_api/know_me/tests/models/test_media_resource_category_model.py
km_api/know_me/tests/serializers/test_media_resource_category_serializer.py
km_api/know_me/tests/views/integration/test_media_resource_category_detail_view.py
km_api/know_me/tests/views/integration/test_media_resource_category_list_view.py
km_api/know_me/tests/views/test_media_resource_category_detail_view.py
km_api/know_me/tests/views/test_media_resource_category_list_view.py
km_api/know_me/urls.py
km_api/know_me/views.py

Closes #217 
This PR adds two new endpoints for managing media resource categories. The first allows for listing and creating categories for a specific Know Me user. The second allows for fetching, updating, or deleting a specific category.

Add endpoints for managing media resource categories

---

docs/changelog.rst
km_api/know_me/models.py
km_api/know_me/profile/tests/serializers/test_list_entry_serializer.py
km_api/know_me/profile/tests/serializers/test_media_resource_category_serializer.py
km_api/know_me/profile/tests/serializers/test_media_resource_serializer.py
km_api/know_me/profile/tests/serializers/test_profile_item_serializer.py
km_api/know_me/profile/tests/serializers/test_profile_list_serializer.py
km_api/know_me/profile/tests/serializers/test_profile_topic_serializer.py
km_api/know_me/tests/models/test_km_user_model.py

Closes #261 
This PR fixes the overly strict permissions on `KMUser` instances. Users granted access through an accessor now have the proper access levels.

Fix strict KMUser permissions.

---

docs/changelog.rst
km_api/know_me/profile/models.py
km_api/know_me/profile/tests/models/test_profile_model.py

Closes #262
Read access to private profiles now requires the requesting user to have
admin rights if they are a shared user.

Fix permissions for private profiles.

---

km_api/know_me/profile/filters.py
km_api/know_me/profile/tests/filters/test_profile_filter_backend.py
km_api/know_me/profile/tests/views/test_profile_list_view.py
km_api/know_me/profile/views.py

Fixes #262
Private profiles are no longer listed for users that don't actually
have permission to view that profile.

Fix private profile listing

---

docs/changelog.rst
km_api/account/serializers.py
km_api/account/tests/serializers/test_user_info_serializer.py
km_api/know_me/journal/models.py
km_api/know_me/journal/permissions.py
km_api/know_me/journal/serializers.py
km_api/know_me/journal/tests/integration/test_entry_comment_list_view.py
km_api/know_me/journal/tests/models/test_entry_comment_model.py
km_api/know_me/journal/tests/models/test_entry_model.py
km_api/know_me/journal/tests/permissions/test_has_entry_comment_list_permissions.py
km_api/know_me/journal/tests/serializers/test_entry_comment_serializer.py
km_api/know_me/journal/tests/serializers/test_entry_detail_serializer.py
km_api/know_me/journal/tests/serializers/test_entry_list_serializer.py
km_api/know_me/journal/tests/views/test_entry_comment_list_view.py
km_api/know_me/journal/urls.py
km_api/know_me/journal/views.py

Closes #249 
This PR adds an endpoint for listing the comments of a journal entry as well as creating a new comment. To assist in this process, we also created a new user serializer that only returns non-sensitive information about the user. We can use this new serializer anywhere we need to display information about one user to another user.

Add endpoint for listing and creating comments of a journal entry

---

docs/changelog.rst
km_api/know_me/serializers.py
km_api/know_me/tests/serializers/test_km_user_detail_serializer.py
km_api/know_me/tests/serializers/test_km_user_list_serializer.py

Closes #276 
Rather than only returning the URLs for additional related resources in
the detail view for a Know Me user, we now return them from the user
list endpoint. This allows clients to obtain these URLs without making a
separate request for each user.

Return URLs in Know Me user list endpoint.

---

km_api/km_api/urls.py

Closes #285 
By adding 'public=False' when generating the docs, we can include a
request when instantiating our views which avoids problems when checking
attributes of the request.

Fix documentation generation.

---

km_api/km_api/urls.py
km_api/know_me/journal/tests/views/test_entry_list_view.py
km_api/know_me/journal/views.py

Fixes #285
Our previous fix for the documentation generation resulted in endpoints
being excluded from the docs. The new fix means that we will have to
check for 'request is None' in any view code that is used by the
generated docs.

Fix missing endpoints in documentation.

---

docs/changelog.rst
km_api/know_me/profile/serializers.py
km_api/know_me/profile/tests/integration/test_profile_item_detail_view.py
km_api/know_me/profile/tests/integration/test_profile_item_list_view.py
km_api/know_me/profile/tests/integration/test_profile_topic_detail_view.py
km_api/know_me/profile/tests/integration/test_profile_topic_list_view.py
km_api/know_me/profile/tests/serializers/test_list_entry_serializer.py
km_api/know_me/profile/tests/serializers/test_profile_detail_serializer.py
km_api/know_me/profile/tests/serializers/test_profile_item_detail_serializer.py
km_api/know_me/profile/tests/serializers/test_profile_item_list_serializer.py
km_api/know_me/profile/tests/serializers/test_profile_list_serializer.py
km_api/know_me/profile/tests/serializers/test_profile_topic_detail_serializer.py
km_api/know_me/profile/tests/serializers/test_profile_topic_list_serializer.py
km_api/know_me/profile/tests/views/test_profile_item_detail_view.py
km_api/know_me/profile/tests/views/test_profile_item_list_view.py
km_api/know_me/profile/tests/views/test_profile_topic_detail_view.py
km_api/know_me/profile/tests/views/test_profile_topic_list_view.py
km_api/know_me/profile/views.py

Closes #258
The serializers responsible for returning different parts of a profile
have been split into list and detail variants. The detail variants
include the same information as the list serializers with the next level
of the profile hierarchy included. For example, the profile topic detail
serializer includes the topic's items.
This change was made to avoid potential future performance issues
resulting from returning an entire profile in one call.

Split profile serializers

---

km_api/know_me/journal/serializers.py
km_api/know_me/journal/tests/serializers/test_entry_detail_serializer.py
km_api/know_me/journal/tests/serializers/test_entry_list_serializer.py
km_api/know_me/journal/tests/views/test_entry_list_view.py
km_api/know_me/journal/views.py

Fixes #291 
Closes #293 
The entry list serializer now returns the entry's text, a link to its attachment, and the number of comments it has.

Add missing fields to entry serializer

---

km_api/mailing_list/mailchimp_utils.py
km_api/mailing_list/tests/mailchimp_utils/test_member_create.py
km_api/mailing_list/tests/mailchimp_utils/test_member_update.py
requirements/base.txt

Fixes #307
It appears the exception raised when trying to create a user who exists
has changed, so we now catch the correct exception.

Fix issue with creating mailchimp user.

---

.gitignore
docs/changelog.rst
km_api/know_me/profile/serializers.py
km_api/know_me/profile/tests/integration/test_profile_item_detail_view.py
km_api/know_me/profile/tests/serializers/test_profile_item_detail_serializer.py

Closes #321
By passing in an empty string (or null value), a profile item can now be set to have no attached media resource.

Allow profile item media resource detachment.

---

docs/changelog.rst
km_api/know_me/tests/views/test_km_user_list_view.py
km_api/know_me/views.py

Closes #332 
Know Me users are automatically created for each registered user, so we
don't need an endpoint to manually create them.

Remove endpoint for creating Know Me users.

---

docs/changelog.rst
km_api/know_me/serializers.py
km_api/know_me/tests/serializers/test_km_user_list_serializer.py
km_api/know_me/tests/views/test_km_user_list_view.py
km_api/know_me/views.py

Closes #326
Modified the order of the queryset returned by the Know Me user list
view to return the KM User belonging to the requesting user first.

Return the requesting user's KM user first.

---

docs/changelog.rst
km_api/know_me/models.py
km_api/know_me/tests/models/test_km_user_accessor_model.py
km_api/know_me/tests/serializers/test_km_user_accessor_serializer.py

Now both the user who created the accessor and the user granted access
by the accessor can destroy it.
Closes #347

Fix accessor delete permissions.

---

docs/changelog.rst
km_api/know_me/tests/views/test_km_user_list_view.py
km_api/know_me/views.py

Closes #352
This bug had the same root cause as #343, so the fix was as simple as adding a `distinct()` call to the query.

Fix duplicates in Know Me user list

---

docs/changelog.rst
km_api/know_me/serializers.py
km_api/know_me/tests/serializers/test_km_user_accessor_serializer.py
km_api/know_me/tests/serializers/test_km_user_info_serializer.py

Closes #354
The accessor serializer now includes the name and image of the Know Me user it grants access to.

Add Know Me user info to accessor response

---

docs/changelog.rst
km_api/know_me/factories.py
km_api/know_me/models.py
km_api/know_me/templates/know_me/emails/invite.txt
km_api/know_me/tests/models/test_km_user_accessor_model.py
km_api/know_me/tests/models/test_km_user_model.py

Closes #236
When a Know Me user is shared through the creation of an accessor, the
user who the accessor grants access to is sent an email notification.

Add email notifications for accessor invites.

---

Dockerfile
docker-entrypoint.sh

Create the database role used by the application within the `migrate` command. This simplifies the requirements for deploying the application because we no longer need to connect to the database and add the role during the provisioning process.

Create app db user role during migration

---

km_api/know_me/subscriptions.py

Closes #424
If we receive an Apple receipt for an unknown product, the log message
that is produced is now of level `INFO` rather than `WARNING`.

Downgrade log level of invalid product message.

---

km_api/know_me/serializers/subscription_serializers.py

Closes #421
Mark the Apple receipt expiration time field as read only so it does not appear as a parameter in the documentation.

Mark apple receipt expiration time as read only

---

km_api/conftest.py
km_api/functional_tests/know_me/users/test_list_know_me_users.py
km_api/functional_tests/serialization_helpers.py
km_api/know_me/conftest.py
km_api/know_me/tests/views/test_km_user_list_view.py
km_api/know_me/views.py

Closes #402
When listing Know Me users that the requesting user has access to, the only shared users that are returned are the ones who have an active premium subscription. The requesting user's Know Me user is returned regardless of subscription status.

Only list shared Know Me users with premium.

---

km_api/functional_tests/know_me/accessors/test_create_accessor.py
km_api/functional_tests/know_me/accessors/test_list_accessors.py
km_api/functional_tests/serialization_helpers.py
km_api/know_me/permissions.py
km_api/know_me/tests/permissions/test_has_premium.py
km_api/know_me/tests/views/test_accessor_list_view.py
km_api/know_me/views.py

Closes #419 
In order to list or add accessors granting others access to their profile, a user must have an active premium subscription.

Require premium to list/add followers

---

.coveragerc

Just because it is difficult to test some things doesn't mean they should not be included in the coverage report.

Include more source files in coverage report

---

km_api/factories.py
km_api/functional_tests/know_me/subscriptions/test_transfer_subscription.py
km_api/know_me/serializers/subscription_serializers.py
km_api/know_me/tests/serializers/test_subscription_transfer_serializer.py
km_api/know_me/tests/views/test_subscription_transfer_view.py
km_api/know_me/urls.py
km_api/know_me/views.py

Closes #396 
This endpoint allows a user with an active premium subscription to transfer their subscription to another Know Me user using the recipient's email address.

Add endpoint for transferring a subscription

---

km_api/functional_tests/know_me/subscriptions/test_get_apple_subscription.py
km_api/functional_tests/know_me/subscriptions/test_set_apple_subscription.py
km_api/know_me/models.py
km_api/know_me/serializers/subscription_serializers.py
km_api/know_me/tests/models/test_subscription_apple_data_model.py
km_api/know_me/tests/serializers/test_apple_subscription_serializer.py
km_api/test_utils/__init__.py

Fixes #444
Fix issues related to database integrity issues when uploading Apple receipts for multiple users. The root cause was that we were not saving the hash of the receipt data (which is the field we have our unique constraint on) which caused an error as soon as the second receipt (with a blank hash field) was added.

Fix issue with adding Apple receipts for multiple users

---

km_api/know_me/management/commands/updatesubscriptions.py
km_api/know_me/tests/management/commands/test_updatesubscriptions_command.py

Closes #445
When updating subscriptions, any subscriptions that do not have an associated receipt are deactivated. This is a defense against cases where we forget to deactivate a subscription once its associated receipt
is deleted.

Handle orphan subscriptions during update process

---

km_api/functional_tests/conftest.py
km_api/functional_tests/know_me/subscriptions/test_delete_apple_subscription.py
km_api/functional_tests/know_me/subscriptions/test_transfer_subscription.py
km_api/know_me/factories.py
km_api/know_me/management/commands/updatesubscriptions.py
km_api/know_me/models.py
km_api/know_me/tests/management/commands/test_updatesubscriptions_command.py
km_api/know_me/tests/models/test_subscription_apple_data_model.py
km_api/know_me/tests/views/test_apple_subscription_view.py
km_api/know_me/views.py

Closes #437 
If a user has previously added an Apple receipt for their premium subscription, they can now delete that receipt.

Allow users to delete their Apple receipt

---

km_api/functional_tests/conftest.py
km_api/functional_tests/know_me/subscriptions/test_delete_apple_subscription.py
km_api/functional_tests/know_me/subscriptions/test_get_subscription_overview.py
km_api/functional_tests/know_me/subscriptions/test_transfer_subscription.py
km_api/know_me/journal/tests/serializers/test_apple_receipt_info_serializer.py
km_api/know_me/journal/tests/serializers/test_subscription_serializer.py
km_api/know_me/journal/tests/views/test_subscription_detail_view.py
km_api/know_me/serializers/subscription_serializers.py
km_api/know_me/urls.py
km_api/know_me/views.py

Closes #380
Users can now view an overview of their subscription to get information such as if the subscription is active and what type of receipt is backing the subscription.

Add endpoint to get info about a subscription

---

km_api/functional_tests/know_me/subscriptions/test_query_apple_receipt_exists.py
km_api/know_me/tests/views/test_apple_receipt_query_view.py
km_api/know_me/urls.py
km_api/know_me/views.py

Closes #439
API consumers can now check for the existence of an Apple receipt by providing the hash of its receipt data.

Add endpoint to check for Apple receipt existence

---

km_api/functional_tests/conftest.py
km_api/know_me/journal/views.py
km_api/pytest.ini

Closes #435
Fixed warnings due to `filter_fields` being renamed to `filterset_fields`. Additionally configured pytest to fail when warnings are emitted.

Fix warnings from `filter_fields` deprecation

---

pyproject.toml

Closes #434 
Fix usage of the `--py36` flag for `black` in favor of `--target-version py36`.

Fix usage of deprecated option for black

---

docs/deployment.rst
km_api/km_api/settings.py

Closes #459 
Instead of always attempting to get the IP address of an ECS task and just continuing if we fail, we now require an environment variable to be set in order for us to get the IP.
The previous behavior was causing the slow CI builds because the network request to get the IP address of the ECS task had to timeout before we could continue and that took approximately 2 minutes per pytest invocation.

Gate ECS IP check behind environment flag

---

km_api/functional_tests/know_me/subscriptions/test_get_subscription_overview.py
km_api/know_me/journal/tests/serializers/test_apple_receipt_info_serializer.py
km_api/know_me/journal/tests/serializers/test_subscription_serializer.py
km_api/know_me/serializers/subscription_serializers.py

Closes #478 
The overview was using the wrong model to display information about the Apple receipt backing a subscription.

Fix subscription overview serializer

---

km_api/functional_tests/know_me/subscriptions/test_query_apple_receipt_exists.py
km_api/know_me/serializers/subscription_serializers.py
km_api/know_me/tests/serializers/test_apple_receipt_query_serializer.py
km_api/know_me/tests/views/test_apple_receipt_query_view.py
km_api/know_me/views.py

Closes #477
The email address of the Know Me user who owns an Apple receipt is now returned from the Apple receipt query endpoint.

Add email address to Apple receipt query response

---

.idea/vcs.xml
km_api/functional_tests/know_me/subscriptions/test_set_apple_subscription.py
km_api/know_me/serializers/subscription_serializers.py
km_api/know_me/tests/serializers/test_apple_receipt_serializer.py

Closes #481
Uploading an expired Apple subscription no longer activates the user's premium subscription.

Fix expired Apple receipts activating premium

---

km_api/functional_tests/know_me/subscriptions/test_transfer_subscription.py
km_api/know_me/serializers/subscription_serializers.py
km_api/know_me/tests/serializers/test_subscription_transfer_serializer.py

Closes #493
The transfer process was using the old model of tracking Apple receipts
to check for an existing Apple subscription. This commit corrects the
check to use the updated model.

Fix issue with transfering subscriptions

---

km_api/functional_tests/know_me/subscriptions/test_query_apple_receipt_exists.py
km_api/know_me/serializers/subscription_serializers.py
km_api/know_me/tests/permissions/test_has_premium.py
km_api/know_me/tests/serializers/test_apple_receipt_query_serializer.py
km_api/know_me/tests/views/test_apple_receipt_query_view.py
km_api/know_me/views.py

Closes #497
Querying for Apple receipts now uses the original transaction ID to
check for existence rather than comparing receipt data hashes.

Implement new method of querying Apple receipts

---

km_api/functional_tests/know_me/subscriptions/test_get_apple_subscription.py
km_api/functional_tests/know_me/subscriptions/test_get_subscription_overview.py
km_api/functional_tests/know_me/subscriptions/test_set_apple_subscription.py
km_api/know_me/journal/tests/serializers/test_apple_receipt_info_serializer.py
km_api/know_me/serializers/subscription_serializers.py
km_api/know_me/tests/serializers/test_apple_receipt_serializer.py

Closes #499
This PR removes all information pertaining to the hash of an Apple receipt's data from responses.

Remove hash fields from Apple receipt responses

---

km_api/functional_tests/serialization_helpers.py
km_api/know_me/serializers/__init__.py
km_api/know_me/tests/serializers/test_km_user_list_serializer.py

Closes #488
The list and detail representations of a Know Me user now include an `is_legacy_user` flag.

Add legacy user flag to Know Me users

---

km_api/functional_tests/know_me/subscriptions/test_set_apple_subscription.py
km_api/know_me/management/commands/updatesubscriptions.py
km_api/know_me/subscriptions.py
km_api/know_me/tests/management/commands/test_updatesubscriptions_command.py
km_api/know_me/tests/subscriptions/test_validate_apple_receipt_response.py

Closes #474
Receipts cancelled by Apple customer support are now correctly handled.
Attempting to upload a receipt that has been cancelled will now reject
the upload, and cancelled receipts are deleted by the background job
used to update subscriptions.

Add logic to handle cancelled Apple receipts

---

km_api/functional_tests/know_me/subscriptions/test_query_apple_receipt_exists.py
km_api/know_me/urls.py

Closes #505
Querying for an Apple receipt is now only available at the URL:
/know-me/subscription/apple/query/

Restrict URL for Apple receipt queries

---

km_api/functional_tests/serialization_helpers.py
km_api/know_me/serializers/__init__.py
km_api/know_me/tests/serializers/test_km_user_info_serializer.py

Closes #512
The Know Me user representation returned with an accessor now includes
the ID of the user.

Add Know Me user ID to accessor representation
